/loadout/wizard_federation //Wizard federation antag
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers/random,
		/obj/item/clothing/undertop/underwear/shirt/random,
		/obj/item/clothing/pants/normal/wizard,
		/obj/item/clothing/shirt/normal,
		/obj/item/clothing/overwear/coat/wizard/purple,
		/obj/item/clothing/feet/socks/knee,
		/obj/item/clothing/feet/socks/knee,
		/obj/item/clothing/feet/shoes/sandal,
		/obj/item/clothing/feet/shoes/sandal/left,
		/obj/item/clothing/head/hat/wizard/purple,
		/obj/item/clothing/neck/tie/red,
		/obj/item/clothing/ears/headset,
		/obj/item/clothing/belt/storage/colored/purple,
		/obj/item/clothing/back/storage/dufflebag/poly/wizard,
		/obj/item/storage/pouch/triple/black,
		/obj/item/storage/pouch/double/black,
		/obj/item/weapon/melee/torch,
		/obj/item/currency/magic_token/max,
		/obj/item/currency/magic_token/max,
		/obj/item/currency/magic_token/max,
		/obj/item/currency/magic_token/max,
		/obj/item/currency/magic_token/max
	)