/class/default
	name = "Default"
	desc = "This is a template. You shouldn't see this."
	id = "default"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 5,
		ATTRIBUTE_VITALITY = 5,
		ATTRIBUTE_FORTITUDE = 5,

		ATTRIBUTE_INTELLIGENCE = 5,
		ATTRIBUTE_RESOLVE = 5,
		ATTRIBUTE_WILLPOWER = 5,

		ATTRIBUTE_DEXTERITY = 5,
		ATTRIBUTE_AGILITY = 5,
		ATTRIBUTE_ENDURANCE = 5,

		ATTRIBUTE_LUCK = 50
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		SKILL_DODGE = 5,
		SKILL_STEALTH = 5,
		SKILL_ATHLETICS = 5,
		SKILL_INSTINCT = 5,
		SKILL_PARRY = 5,

		SKILL_MELEE = 5,
		SKILL_BLOCK = 5,
		SKILL_UNARMED = 5,
		SKILL_PRAYER = 5,
		SKILL_ARMOR = 5,
		SKILL_RECOVERY = 5,

		SKILL_MEDICINE = 0,
		SKILL_MAGIC_OFFENSIVE = 5,
		SKILL_MAGIC_SUPPORT = 5,
		SKILL_MAGIC_DEFENSIVE = 5,
		SKILL_MAGIC_REALITY = 5,
		SKILL_MAGIC_CHAOS = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)

