/class/default
	name = "Default"
	desc = "This is a template. You shouldn't see this."
	id = "default"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 0,
		ATTRIBUTE_VITALITY = 0,
		ATTRIBUTE_FORTITUDE = 0,

		ATTRIBUTE_INTELLIGENCE = 0,
		ATTRIBUTE_RESOLVE = 0,
		ATTRIBUTE_WILLPOWER = 0,

		ATTRIBUTE_DEXTERITY = 0,
		ATTRIBUTE_AGILITY = 0,
		ATTRIBUTE_ENDURANCE = 0,

		ATTRIBUTE_LUCK = 50
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 0,
		SKILL_DODGE = 0,
		SKILL_STEALTH = 0,
		SKILL_ATHLETICS = 0,
		SKILL_INSTINCT = 0,
		SKILL_PARRY = 0,

		SKILL_MELEE = 0,
		SKILL_BLOCK = 0,
		SKILL_UNARMED = 0,
		SKILL_PRAYER = 0,
		SKILL_ARMOR = 0,
		SKILL_RECOVERY = 0,

		SKILL_MEDICINE = 0,
		SKILL_MAGIC_OFFENSIVE = 0,
		SKILL_MAGIC_SUPPORT = 0,
		SKILL_MAGIC_DEFENSIVE = 0,
		SKILL_MAGIC_REALITY = 0,
		SKILL_MAGIC_CHAOS = 0,

		SKILL_ALCHEMY = 0,
		SKILL_COOKING = 0,
		SKILL_CRAFTING = 0,
		SKILL_ENCHANTING = 0
	)

