/class/npc/robust

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 100,
		ATTRIBUTE_VITALITY = 100,
		ATTRIBUTE_FORTITUDE = 100,

		ATTRIBUTE_INTELLIGENCE = 100,
		ATTRIBUTE_WISDOM = 100,
		ATTRIBUTE_WILLPOWER = 100,

		ATTRIBUTE_DEXTERITY = 100,
		ATTRIBUTE_RESILIENCE = 100,
		ATTRIBUTE_ENDURANCE = 100,

		ATTRIBUTE_LUCK = 100
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 100,
		//SKILL_DODGE  = 100,
		SKILL_PRECISION = 100,
		SKILL_SURVIVAL = 100,

		SKILL_MELEE = 100,
		//SKILL_BLOCK = 100,
		SKILL_UNARMED = 100,
		SKILL_PRAYER = 100,

		SKILL_MEDICINE = 100,
		SKILL_MAGIC = 100,
		SKILL_SORCERY = 100,
		//SKILL_PARRY  = 100,

		SKILL_ALCHEMY = 100,
		SKILL_COOKING = 100,
		SKILL_CRAFTING = 100,
		SKILL_ENCHANTING = 100
	)

