/class/ash_drake

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 90,
		ATTRIBUTE_VITALITY = 50,
		ATTRIBUTE_FORTITUDE = 80,

		ATTRIBUTE_INTELLIGENCE = 30,
		ATTRIBUTE_WISDOM = 50,
		ATTRIBUTE_WILLPOWER = 50,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_RESILIENCE = 70,
		ATTRIBUTE_ENDURANCE = 70,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 25,
		SKILL_PRECISION = 10,
		SKILL_SURVIVAL = 50,

		SKILL_MELEE = 5,
		//SKILL_BLOCK = 50,
		SKILL_UNARMED = 30,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 25,
		SKILL_SORCERY = 10,
		//SKILL_PARRY  = 25,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)