
/class/ashwalker

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 15,
		ATTRIBUTE_VITALITY = 10,
		ATTRIBUTE_FORTITUDE = 15,

		ATTRIBUTE_INTELLIGENCE = 5,
		ATTRIBUTE_WISDOM = 15,
		ATTRIBUTE_WILLPOWER = 15,

		ATTRIBUTE_DEXTERITY = 15,
		ATTRIBUTE_RESILIENCE = 15,
		ATTRIBUTE_ENDURANCE = 20,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 25,
		SKILL_PRECISION = 25,
		SKILL_SURVIVAL = 40,

		SKILL_MELEE = 25,
		//SKILL_BLOCK = 20,
		SKILL_UNARMED = 20,
		SKILL_PRAYER = 20,

		SKILL_MEDICINE = 15,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 20,
		//SKILL_PARRY  = 20,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)