/class/bear
	name = "Bear"
	desc = "Unbearable"
	id = "bear"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 30,
		ATTRIBUTE_VITALITY = 25,
		ATTRIBUTE_FORTITUDE = 20,

		ATTRIBUTE_INTELLIGENCE = 5,
		ATTRIBUTE_RESOLVE = 5,
		ATTRIBUTE_WILLPOWER = 5,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_AGILITY = 10,
		ATTRIBUTE_ENDURANCE = 20,

		ATTRIBUTE_LUCK = 25
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 1,
		SKILL_DODGE = 1,
		SKILL_STEALTH = 15,
		SKILL_ATHLETICS = 1,
		SKILL_INSTINCTS = 1,
		SKILL_PARRY = 1,

		SKILL_MELEE = 1,
		SKILL_BLOCK = 10,
		SKILL_UNARMED = 25,
		SKILL_PRAYER = 1,
		SKILL_ARMOR = 5,
		SKILL_RECOVERY = 5,

		SKILL_MEDICINE = 1,
		SKILL_MAGIC_OFFENSIVE = 1,
		SKILL_MAGIC_SUPPORT = 1,
		SKILL_MAGIC_DEFENSIVE = 1,
		SKILL_MAGIC_REALITY = 1,
		SKILL_MAGIC_CHAOS = 1,

		SKILL_ALCHEMY = 1,
		SKILL_COOKING = 1,
		SKILL_CRAFTING = 1,
		SKILL_ENCHANTING = 1
	)
