/class/beepsky

	attributes = list(
		ATTRIBUTE_STRENGTH = 35,
		ATTRIBUTE_VITALITY = 40,
		ATTRIBUTE_FORTITUDE = 75,

		ATTRIBUTE_INTELLIGENCE = 75,
		ATTRIBUTE_WISDOM = 25,
		ATTRIBUTE_WILLPOWER = 15,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_RESILIENCE = 20,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 100
	)

	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 5,
		SKILL_PRECISION = 25,
		SKILL_SURVIVAL = 5,

		SKILL_MELEE = 25,
		//SKILL_BLOCK = 40,
		SKILL_UNARMED = 25,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		//SKILL_PARRY  = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)