/class/bull

	attributes = list(
		ATTRIBUTE_STRENGTH = 60,
		ATTRIBUTE_VITALITY = 30,
		ATTRIBUTE_FORTITUDE = 60,

		ATTRIBUTE_INTELLIGENCE = 10,
		ATTRIBUTE_WISDOM = 10,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_RESILIENCE = 75,
		ATTRIBUTE_ENDURANCE = 75,

		ATTRIBUTE_LUCK = 40
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 5,
		SKILL_PRECISION = 50,
		SKILL_SURVIVAL = 40,

		SKILL_MELEE = 10,
		//SKILL_BLOCK = 10,
		SKILL_UNARMED = 20,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		//SKILL_PARRY  = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)