/class/carp

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 20,
		ATTRIBUTE_VITALITY = 10,
		ATTRIBUTE_FORTITUDE = 10,

		ATTRIBUTE_INTELLIGENCE = 5,
		ATTRIBUTE_WISDOM = 5,
		ATTRIBUTE_WILLPOWER = 5,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_RESILIENCE = 20,
		ATTRIBUTE_ENDURANCE = 20,

		ATTRIBUTE_LUCK = 5
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 10,
		SKILL_PRECISION = 10,
		SKILL_SURVIVAL = 25,

		SKILL_MELEE = 5,
		//SKILL_BLOCK = 10,
		SKILL_UNARMED = 25,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		//SKILL_PARRY  = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)