/class/colossus

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 50,
		ATTRIBUTE_VITALITY = 50,
		ATTRIBUTE_FORTITUDE = 60,

		ATTRIBUTE_INTELLIGENCE = 50,
		ATTRIBUTE_WISDOM = 75,
		ATTRIBUTE_WILLPOWER = 75,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_RESILIENCE = 20,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 25,
		//SKILL_DODGE  = 5,
		SKILL_PRECISION = 25,
		SKILL_SURVIVAL = 50,

		SKILL_MELEE = 25,
		//SKILL_BLOCK = 25,
		SKILL_UNARMED = 10,
		SKILL_PRAYER = 75,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 50,
		SKILL_SORCERY = 50,
		//SKILL_PARRY  = 25,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)