/class/crab
	name = "Crab"
	desc = "CRAB PEOPLE."
	id = "crab"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 5,
		ATTRIBUTE_VITALITY = 5,
		ATTRIBUTE_FORTITUDE = 1,

		ATTRIBUTE_INTELLIGENCE = 1,
		ATTRIBUTE_RESOLVE = 1,
		ATTRIBUTE_WILLPOWER = 1,

		ATTRIBUTE_DEXTERITY = 5,
		ATTRIBUTE_AGILITY = 5,
		ATTRIBUTE_ENDURANCE = 5,

		ATTRIBUTE_LUCK = 5
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 1,
		SKILL_DODGE = 5,
		SKILL_STEALTH = 1,
		SKILL_ATHLETICS = 1,
		SKILL_INSTINCTS = 1,
		SKILL_PARRY = 5,

		SKILL_MELEE = 5,
		SKILL_BLOCK = 5,
		SKILL_UNARMED = 5,
		SKILL_PRAYER = 1,
		SKILL_ARMOR = 10,
		SKILL_RECOVERY = 1,

		SKILL_MEDICINE = 1,
		SKILL_MAGIC_OFFENSIVE = 1,
		SKILL_MAGIC_SUPPORT = 1,
		SKILL_MAGIC_DEFENSIVE = 1,
		SKILL_MAGIC_REALITY = 1,
		SKILL_MAGIC_CHAOS = 1,

		SKILL_ALCHEMY = 1,
		SKILL_COOKING = 1,
		SKILL_CRAFTING = 1,
		SKILL_ENCHANTING = 1
	)

/class/crab_king
	name = "Crab King"
	desc = "CRAB PEOPLE."
	id = "crab_king"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_VITALITY = ATTRIBUTE_STARTING_PRIMARY,
		ATTRIBUTE_FORTITUDE = ATTRIBUTE_STARTING_SECONDARY,

		ATTRIBUTE_INTELLIGENCE = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_RESOLVE = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_WILLPOWER = ATTRIBUTE_STARTING_NONE,

		ATTRIBUTE_DEXTERITY = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_AGILITY = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_ENDURANCE = ATTRIBUTE_STARTING_TERTIARY,

		ATTRIBUTE_LUCK = 25
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = SKILL_STARTING_NONE,
		SKILL_DODGE = SKILL_STARTING_NONE,
		SKILL_STEALTH = SKILL_STARTING_SECONDARY,
		SKILL_ATHLETICS = SKILL_STARTING_TERTIARY,
		SKILL_INSTINCTS = SKILL_STARTING_TERTIARY,
		SKILL_PARRY = SKILL_STARTING_TERTIARY,

		SKILL_MELEE = SKILL_STARTING_SECONDARY,
		SKILL_BLOCK = SKILL_STARTING_PRIMARY,
		SKILL_UNARMED = SKILL_STARTING_PRIMARY,
		SKILL_PRAYER = SKILL_STARTING_NONE,
		SKILL_ARMOR = SKILL_STARTING_PRIMARY,
		SKILL_RECOVERY = SKILL_STARTING_SECONDARY,

		SKILL_MEDICINE = SKILL_STARTING_NONE,
		SKILL_MAGIC_OFFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_SUPPORT = SKILL_STARTING_NONE,
		SKILL_MAGIC_DEFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_REALITY = SKILL_STARTING_NONE,
		SKILL_MAGIC_CHAOS = SKILL_STARTING_NONE,

		SKILL_ALCHEMY = SKILL_STARTING_NONE,
		SKILL_COOKING = SKILL_STARTING_NONE,
		SKILL_CRAFTING = SKILL_STARTING_NONE,
		SKILL_ENCHANTING = SKILL_STARTING_NONE
	)




