/class/crab

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 5,
		ATTRIBUTE_VITALITY = 5,
		ATTRIBUTE_FORTITUDE = 1,

		ATTRIBUTE_INTELLIGENCE = 1,
		ATTRIBUTE_WISDOM = 1,
		ATTRIBUTE_WILLPOWER = 1,

		ATTRIBUTE_DEXTERITY = 5,
		ATTRIBUTE_RESILIENCE = 5,
		ATTRIBUTE_ENDURANCE = 5,

		ATTRIBUTE_LUCK = 5
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 1,
		//SKILL_DODGE  = 5,
		SKILL_PRECISION = 10,
		SKILL_SURVIVAL = 10,

		SKILL_MELEE = 5,
		//SKILL_BLOCK = 5,
		SKILL_UNARMED = 5,
		SKILL_PRAYER = 1,

		SKILL_MEDICINE = 1,
		SKILL_MAGIC = 1,
		SKILL_SORCERY = 1,
		//SKILL_PARRY  = 1,

		SKILL_ALCHEMY = 1,
		SKILL_COOKING = 1,
		SKILL_CRAFTING = 1,
		SKILL_ENCHANTING = 1
	)


/class/crab/king

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 50,
		ATTRIBUTE_VITALITY = 50,
		ATTRIBUTE_FORTITUDE = 20,

		ATTRIBUTE_INTELLIGENCE = 10,
		ATTRIBUTE_WISDOM = 10,
		ATTRIBUTE_WILLPOWER = 20,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_RESILIENCE = 10,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 40
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 1,
		//SKILL_DODGE  = 1,
		SKILL_PRECISION = 40,
		SKILL_SURVIVAL = 50,

		SKILL_MELEE = 40,
		//SKILL_BLOCK = 100,
		SKILL_UNARMED = 30,
		SKILL_PRAYER = 10,

		SKILL_MEDICINE = 10,
		SKILL_MAGIC = 10,
		SKILL_SORCERY = 10,
		//SKILL_PARRY  = 25,

		SKILL_ALCHEMY = 1,
		SKILL_COOKING = 1,
		SKILL_CRAFTING = 1,
		SKILL_ENCHANTING = 1
	)
