/class/daddy

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 16,
		ATTRIBUTE_VITALITY = 48,
		ATTRIBUTE_FORTITUDE = 12,

		ATTRIBUTE_INTELLIGENCE = 8,
		ATTRIBUTE_WISDOM = 11,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_RESILIENCE = 12,
		ATTRIBUTE_ENDURANCE = 66,

		ATTRIBUTE_LUCK = 50
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 100, //YES
		SKILL_PRECISION = 5,
		SKILL_SURVIVAL = 50,

		SKILL_MELEE = 50,
		//SKILL_BLOCK = 25,
		SKILL_UNARMED = 5,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 50,
		//SKILL_PARRY  = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)