/class/goliath
	name = "Goliath"
	desc = "This is a template. You shouldn't see this."
	id = "goliath"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 40,
		ATTRIBUTE_VITALITY = 20,
		ATTRIBUTE_FORTITUDE = 50,

		ATTRIBUTE_INTELLIGENCE = 10,
		ATTRIBUTE_RESOLVE = 20,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_AGILITY = 15,
		ATTRIBUTE_ENDURANCE = 30,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		SKILL_DODGE = 5,
		SKILL_STEALTH = 40,
		SKILL_ATHLETICS = 25,
		SKILL_INSTINCTS = 25,
		SKILL_PARRY = 5,

		SKILL_MELEE = 10,
		SKILL_BLOCK = 30,
		SKILL_UNARMED = 30,
		SKILL_PRAYER = 5,
		SKILL_ARMOR = 40,
		SKILL_RECOVERY = 30,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC_OFFENSIVE = 5,
		SKILL_MAGIC_SUPPORT = 5,
		SKILL_MAGIC_DEFENSIVE = 5,
		SKILL_MAGIC_REALITY = 5,
		SKILL_MAGIC_CHAOS = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)