/class/spider
	name = "Spider"
	desc = "For Spider."
	id = "spider"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 15,
		ATTRIBUTE_VITALITY = 15,
		ATTRIBUTE_FORTITUDE = 10,

		ATTRIBUTE_INTELLIGENCE = 1,
		ATTRIBUTE_RESOLVE = 1,
		ATTRIBUTE_WILLPOWER = 1,

		ATTRIBUTE_DEXTERITY = 25,
		ATTRIBUTE_AGILITY = 25,
		ATTRIBUTE_ENDURANCE = 5,

		ATTRIBUTE_LUCK = 10
	)

	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 1,
		SKILL_DODGE = 1,
		SKILL_STEALTH = 25,
		SKILL_ATHLETICS = 1,
		SKILL_INSTINCTS = 1,
		SKILL_PARRY = 5,

		SKILL_MELEE = 1,
		SKILL_BLOCK = 10,
		SKILL_UNARMED = 10,
		SKILL_PRAYER = 1,
		SKILL_ARMOR = 5,
		SKILL_RECOVERY = 5,

		SKILL_MEDICINE = 1,
		SKILL_MAGIC_OFFENSIVE = 1,
		SKILL_MAGIC_SUPPORT = 1,
		SKILL_MAGIC_DEFENSIVE = 1,
		SKILL_MAGIC_REALITY = 1,
		SKILL_MAGIC_CHAOS = 1,

		SKILL_ALCHEMY = 1,
		SKILL_COOKING = 1,
		SKILL_CRAFTING = 1,
		SKILL_ENCHANTING = 1
	)




