/class/npc/squats
	id = "squats"

	attributes = list(
		ATTRIBUTE_STRENGTH = 30,
		ATTRIBUTE_VITALITY = 20,
		ATTRIBUTE_FORTITUDE = 10,

		ATTRIBUTE_INTELLIGENCE = 25,
		ATTRIBUTE_WISDOM = 10,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 10,
		ATTRIBUTE_AGILITY = 30,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 50
	)

	skills = list(
		SKILL_RANGED = 5,
		SKILL_DODGE = 5,
		SKILL_PRECISION = 30,
		SKILL_SURVIVAL = 5,

		SKILL_MELEE = 40,
		SKILL_BLOCK = 30,
		SKILL_UNARMED = 30,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		SKILL_PARRY = 20,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)

