/class/stand

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 75,
		ATTRIBUTE_VITALITY = 25,
		ATTRIBUTE_FORTITUDE = 50,

		ATTRIBUTE_INTELLIGENCE = 25,
		ATTRIBUTE_WISDOM = 25,
		ATTRIBUTE_WILLPOWER = 25,

		ATTRIBUTE_DEXTERITY = 50,
		ATTRIBUTE_RESILIENCE = 50,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 50
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		//SKILL_DODGE  = 100,
		SKILL_PRECISION = 75,
		SKILL_SURVIVAL = 25,

		SKILL_MELEE = 5,
		//SKILL_BLOCK = 100,
		SKILL_UNARMED = 50,
		SKILL_PRAYER = 25,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		//SKILL_PARRY  = 100,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)