

/class/syndicate_soldier

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 15,
		ATTRIBUTE_VITALITY = 10,
		ATTRIBUTE_FORTITUDE = 15,

		ATTRIBUTE_INTELLIGENCE = 20,
		ATTRIBUTE_WISDOM = 10,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_RESILIENCE = 15,
		ATTRIBUTE_ENDURANCE = 15,

		ATTRIBUTE_LUCK = 5
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 20,
		SKILL_DODGE = 10,
		SKILL_PRECISION = 5,
		SKILL_SURVIVAL = 25,

		SKILL_MELEE = 25,
		SKILL_BLOCK = 15,
		SKILL_UNARMED = 10,
		SKILL_PRAYER = 10,

		SKILL_MEDICINE = 20,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		SKILL_PARRY = 15,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)