/class/xenomorph
	name = "Xenomorph"
	desc = "This is a template. You shouldn't see this."
	id = "xenomorph"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_VITALITY = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_FORTITUDE = ATTRIBUTE_STARTING_TERTIARY,

		ATTRIBUTE_INTELLIGENCE = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_RESOLVE = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_WILLPOWER = ATTRIBUTE_STARTING_NONE,

		ATTRIBUTE_DEXTERITY = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_AGILITY = ATTRIBUTE_STARTING_PRIMARY,
		ATTRIBUTE_ENDURANCE = ATTRIBUTE_STARTING_SECONDARY,

		ATTRIBUTE_LUCK = 50
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = SKILL_STARTING_NONE,
		SKILL_DODGE = SKILL_STARTING_PRIMARY,
		SKILL_STEALTH = SKILL_STARTING_PRIMARY,
		SKILL_ATHLETICS = SKILL_STARTING_PRIMARY,
		SKILL_INSTINCTS = SKILL_STARTING_TERTIARY,
		SKILL_PARRY = SKILL_STARTING_TERTIARY,

		SKILL_MELEE = SKILL_STARTING_NONE,
		SKILL_BLOCK = SKILL_STARTING_SECONDARY,
		SKILL_UNARMED = SKILL_STARTING_SECONDARY,
		SKILL_PRAYER = SKILL_STARTING_NONE,
		SKILL_ARMOR = SKILL_STARTING_SECONDARY,
		SKILL_RECOVERY = SKILL_STARTING_TERTIARY,

		SKILL_MEDICINE = SKILL_STARTING_NONE,
		SKILL_MAGIC_OFFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_SUPPORT = SKILL_STARTING_NONE,
		SKILL_MAGIC_DEFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_REALITY = SKILL_STARTING_NONE,
		SKILL_MAGIC_CHAOS = SKILL_STARTING_NONE,

		SKILL_ALCHEMY = SKILL_STARTING_NONE,
		SKILL_COOKING = SKILL_STARTING_NONE,
		SKILL_CRAFTING = SKILL_STARTING_NONE,
		SKILL_ENCHANTING = SKILL_STARTING_NONE
	)



/class/xenomorph/queen
	name = "Xenomorph Queen"
	desc = "This is a template. You shouldn't see this."
	id = "xenomorph_queen"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = ATTRIBUTE_STARTING_PRIMARY,
		ATTRIBUTE_VITALITY = ATTRIBUTE_STARTING_PRIMARY,
		ATTRIBUTE_FORTITUDE = ATTRIBUTE_STARTING_PRIMARY,

		ATTRIBUTE_INTELLIGENCE = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_RESOLVE = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_WILLPOWER = ATTRIBUTE_STARTING_TERTIARY,

		ATTRIBUTE_DEXTERITY = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_AGILITY = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_ENDURANCE = ATTRIBUTE_STARTING_SECONDARY,

		ATTRIBUTE_LUCK = 50
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = SKILL_STARTING_NONE,
		SKILL_DODGE = SKILL_STARTING_TERTIARY,
		SKILL_STEALTH = SKILL_STARTING_TERTIARY,
		SKILL_ATHLETICS = SKILL_STARTING_TERTIARY,
		SKILL_INSTINCTS = SKILL_STARTING_PRIMARY,
		SKILL_PARRY = SKILL_STARTING_SECONDARY,

		SKILL_MELEE = SKILL_STARTING_NONE,
		SKILL_BLOCK = SKILL_STARTING_SECONDARY,
		SKILL_UNARMED = SKILL_STARTING_SECONDARY,
		SKILL_PRAYER = SKILL_STARTING_NONE,
		SKILL_ARMOR = SKILL_STARTING_PRIMARY,
		SKILL_RECOVERY = SKILL_STARTING_PRIMARY,

		SKILL_MEDICINE = SKILL_STARTING_NONE,
		SKILL_MAGIC_OFFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_SUPPORT = SKILL_STARTING_NONE,
		SKILL_MAGIC_DEFENSIVE = SKILL_STARTING_NONE,
		SKILL_MAGIC_REALITY = SKILL_STARTING_NONE,
		SKILL_MAGIC_CHAOS = SKILL_STARTING_NONE,

		SKILL_ALCHEMY = SKILL_STARTING_NONE,
		SKILL_COOKING = SKILL_STARTING_NONE,
		SKILL_CRAFTING = SKILL_STARTING_NONE,
		SKILL_ENCHANTING = SKILL_STARTING_NONE
	)