/class/xenomorph
	name = "Xenomorph"
	desc = "This is a template. You shouldn't see this."
	id = "xenomorph"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 50,
		ATTRIBUTE_VITALITY = 20,
		ATTRIBUTE_FORTITUDE = 40,

		ATTRIBUTE_INTELLIGENCE = 10,
		ATTRIBUTE_RESOLVE = 20,
		ATTRIBUTE_WILLPOWER = 5,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_AGILITY = 50,
		ATTRIBUTE_ENDURANCE = 40,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		SKILL_DODGE = 50,
		SKILL_STEALTH = 70,
		SKILL_ATHLETICS = 70,
		SKILL_INSTINCTS = 70,
		SKILL_PARRY = 5,

		SKILL_MELEE = 5,
		SKILL_BLOCK = 20,
		SKILL_UNARMED = 50,
		SKILL_PRAYER = 5,
		SKILL_ARMOR = 5,
		SKILL_RECOVERY = 20,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC_OFFENSIVE = 5,
		SKILL_MAGIC_SUPPORT = 5,
		SKILL_MAGIC_DEFENSIVE = 5,
		SKILL_MAGIC_REALITY = 5,
		SKILL_MAGIC_CHAOS = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)



/class/xenomorph/queen
	name = "Xenomorph Queen"
	desc = "This is a template. You shouldn't see this."
	id = "xenomorph_queen"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 80,
		ATTRIBUTE_VITALITY = 60,
		ATTRIBUTE_FORTITUDE = 60,

		ATTRIBUTE_INTELLIGENCE = 50,
		ATTRIBUTE_RESOLVE = 70,
		ATTRIBUTE_WILLPOWER = 70,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_AGILITY = 20,
		ATTRIBUTE_ENDURANCE = 50,

		ATTRIBUTE_LUCK = 25
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 5,
		SKILL_DODGE = 20,
		SKILL_STEALTH = 50,
		SKILL_ATHLETICS = 20,
		SKILL_INSTINCTS = 80,
		SKILL_PARRY = 5,

		SKILL_MELEE = 5,
		SKILL_BLOCK = 40,
		SKILL_UNARMED = 80,
		SKILL_PRAYER = 5,
		SKILL_ARMOR = 40,
		SKILL_RECOVERY = 60,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC_OFFENSIVE = 5,
		SKILL_MAGIC_SUPPORT = 5,
		SKILL_MAGIC_DEFENSIVE = 5,
		SKILL_MAGIC_REALITY = 5,
		SKILL_MAGIC_CHAOS = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)