
//Ranged weapons.
#define HELD_SLOWDOWN_PISTOL 1.05
#define HELD_SLOWDOWN_REVOLVER 1.1

#define HELD_SLOWDOWN_SHOTGUN 1.15
#define HELD_SLOWDOWN_SHOTGUN_SMALL 1.1

#define HELD_SLOWDOWN_SMG 1.15

#define HELD_SLOWDOWN_CROSSBOW 1.2

#define HELD_SLOWDOWN_RIFLE 1.3
#define HELD_SLOWDOWN_RIFLE_SMALL 1.25
#define HELD_SLOWDOWN_RIFLE_LARGE 1.4

#define HELD_SLOWDOWN_SNIPER 1.4
#define HELD_SLOWDOWN_SNIPER_LARGE 1.5

