#define RULE_HUMAN SPECIES_HUMAN
#define RULE_LIZARD SPECIES_REPTILE_FERAL | SPECIES_REPTILE_ADVANCED
#define RULE_DIONAE SPECIES_DIONA
#define RULE_CYBORG SPECIES_CYBORG

#define RULE_SENTIENT_ORGANIC RULE_HUMAN | RULE_LIZARD | RULE_DIONAE

#define RULE_ALL 0xFFFFFF

#define KARMA_OVERALL "all" //Killed/Help players
#define KARMA_CLIENT "client" //Client karma

#define KARMA_HUMAN "human"
#define KARMA_LIZARD "lizard"
#define KARMA_CYBORG "cyborg"
#define KARMA_DIONA "diona"