/loadout/rev/
	spawning_items = list(
		/obj/item/clothing/pants/normal/grey,
		/obj/item/clothing/feet/shoes/winter,
		/obj/item/clothing/feet/shoes/winter/left,
		/obj/item/clothing/back/storage/backpack/explorer,
		/obj/item/clothing/belt/storage/tool
	)

/loadout/rev/classic
	spawning_items = list(
		/obj/item/clothing/pants/normal/grey,
		/obj/item/clothing/overwear/armor/bulletproof,
		/obj/item/clothing/overwear/coat/brown,
		/obj/item/clothing/mask/gas,
		/obj/item/clothing/head/hat/ushanka,
		/obj/item/clothing/hands/gloves/colored/insulated,
		/obj/item/clothing/hands/gloves/colored/insulated/left,
		/obj/item/clothing/feet/shoes/winter,
		/obj/item/clothing/feet/shoes/winter/left,
		/obj/item/clothing/back/storage/backpack/explorer,
		/obj/item/clothing/belt/storage/tool,
		/obj/item/weapon/ranged/bullet/magazine/rifle/ak13,
		/obj/item/magazine/rifle_762_short,
		/obj/item/magazine/rifle_762_short,
		/obj/item/magazine/rifle_762_short,
		/obj/item/magazine/rifle_762_short,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)

/loadout/rev/medium_heavy
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/overwear/armor/slavticool,
		/obj/item/clothing/head/helmet/security/slavticool,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/satchel,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/abakan,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)

/loadout/rev/scout_sniper
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/overwear/armor/slavticool,
		/obj/item/clothing/head/helmet/security/slavticool,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/satchel,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/vintorez,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)

/loadout/rev/heavy
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/overwear/hardsuit/exosuit,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/satchel,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/val,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)

/loadout/rev/special_forces
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/overwear/hardsuit/exosuit,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/back/storage/satchel,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/groza,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/magazine/rifle_939,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)


/loadout/rev/player_antagonist
	spawning_items = list(
		/obj/item/clothing/ears/headset,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/pants/gorka,
		/obj/item/clothing/shirt/gorka,
		/obj/item/clothing/overwear/hardsuit/skat,
		/obj/item/clothing/back/storage/backpack/explorer,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/triple/black/,
		/obj/item/storage/pouch/triple/black/,
		/obj/item/clothing/glasses/sun,
		/obj/item/clothing/hands/gloves/colored/combat,
		/obj/item/clothing/hands/gloves/colored/combat/left,
		/obj/item/clothing/head/hat/skimask/black,
		/obj/item/clothing/mask/gas/mining,
		/obj/item/clothing/neck/mantle/white,
		/obj/item/weapon/ranged/bullet/magazine/rifle/ak12,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/magazine/rifle_545,
		/obj/item/storage/kit/ai3/filled,
		/obj/item/storage/kit/ai3/filled,
		/obj/item/currency/telecrystals/player_antagonist_spawn,
		/obj/item/weapon/ranged/bullet/magazine/pistol/yarygin,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/magazine/pistol_9mm,
		/obj/item/weapon/melee/energy/sword/red
	)
