/loadout/syndicate/ //Operative.
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/triple/black,
		/obj/item/storage/pouch/triple/black,
		/obj/item/weapon/melee/energy/sword/green,
		/obj/item/weapon/ranged/bullet/magazine/pistol/syndie,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm
	)

/loadout/syndicate/soldier
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/head/helmet/security/tactical/advanced,
		/obj/item/clothing/head/hat/skimask/black,
		/obj/item/clothing/overwear/armor/molded_armor,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/carbine,
		/obj/item/weapon/melee/energy/sword/green,
		/obj/item/weapon/ranged/bullet/magazine/pistol/syndie,
		/obj/item/magazine/carbine_223,
		/obj/item/magazine/carbine_223,
		/obj/item/magazine/carbine_223,
		/obj/item/magazine/carbine_223,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/grenade/fuse/fragmentation
	)

/loadout/syndicate/shotgunnner
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/head/helmet/security/tactical/advanced,
		/obj/item/clothing/head/hat/skimask/black,
		/obj/item/clothing/mask/gas/syndicate,
		/obj/item/clothing/overwear/armor/bulletproof,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/shotgun/bulldog,
		/obj/item/weapon/ranged/bullet/magazine/pistol/syndie,
		/obj/item/magazine/shotgun_auto/buckshot,
		/obj/item/magazine/shotgun_auto/buckshot,
		/obj/item/magazine/shotgun_auto/buckshot,
		/obj/item/magazine/shotgun_auto/buckshot,
		/obj/item/magazine/shotgun_auto/buckshot,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/grenade/fuse/fragmentation,
		/obj/item/grenade/fuse/fragmentation
	)

/loadout/syndicate/basic
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/overwear/hardsuit/syndie,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/triple/black,
		/obj/item/weapon/ranged/bullet/magazine/smg/bullpup/standard,
		/obj/item/weapon/melee/energy/sword/green,
		/obj/item/weapon/ranged/bullet/magazine/pistol/syndie,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/grenade/fuse/fragmentation
	)

/loadout/syndicate/advanced
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/overwear/hardsuit/syndie/advanced,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/marksman,
		/obj/item/weapon/melee/energy/sword/green,
		/obj/item/weapon/ranged/bullet/magazine/pistol/high_calibre,
		/obj/item/magazine/rifle_308,
		/obj/item/magazine/rifle_308,
		/obj/item/magazine/rifle_308,
		/obj/item/magazine/pistol_12mm,
		/obj/item/magazine/pistol_12mm,
		/obj/item/grenade/fuse/fragmentation,
		/obj/item/grenade/fuse/fragmentation,
		/obj/item/grenade/fuse/fragmentation
	)

/loadout/syndicate/elite
	spawning_items = list(
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/pants/syndicate,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/overwear/hardsuit/syndie/elite,
		/obj/item/storage/pouch/single/black,
		/obj/item/storage/pouch/single/black,
		/obj/item/weapon/ranged/bullet/magazine/rifle/lmg,
		/obj/item/magazine/lmg_223,
		/obj/item/magazine/lmg_223,
		/obj/item/clothing/belt/storage/colored/black
	)

/loadout/syndicate/player_antagonist
	spawning_items = list(
		/obj/item/clothing/ears/headset/syndicate,
		/obj/item/clothing/undertop/underwear/shirt,
		/obj/item/clothing/underbottom/underwear/boxers,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/feet/socks/ankle,
		/obj/item/clothing/uniform/antag/syndicate,
		/obj/item/clothing/glasses/sun/security/red,
		/obj/item/clothing/head/hat/beret/armored/syndicate,
		/obj/item/clothing/mask/gas/syndicate,
		/obj/item/clothing/overwear/armor/bulletproof,
		/obj/item/clothing/overwear/coat/vest/syndicate,
		/obj/item/clothing/neck/cloak/red,
		/obj/item/clothing/hands/gloves/colored/padded/black,
		/obj/item/clothing/hands/gloves/colored/padded/black/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/storage/pouch/triple/black/,
		/obj/item/storage/pouch/triple/black/,
		/obj/item/weapon/ranged/bullet/magazine/smg/bullpup/standard,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/magazine/smg_45,
		/obj/item/weapon/ranged/bullet/magazine/pistol/syndie,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/magazine/pistol_10mm,
		/obj/item/weapon/melee/energy/sword/green,
		/obj/item/clothing/back/storage/dufflebag/syndicate,
		/obj/item/weapon/melee/torch/flashlight/maglight,
		/obj/item/pinpointer/crew/syndicate,
		/obj/item/container/food/package/junkfood/syndicate,
		/obj/item/container/beaker/can/dr_gibb,
		/obj/item/currency/telecrystals/player_antagonist_spawn,
		/obj/item/fulton_pack
	)


/loadout/syndicate/scientist
	spawning_items = list(
		/obj/item/clothing/pants/normal/black,
		/obj/item/clothing/shirt/syndicate,
		/obj/item/clothing/overwear/coat/labcoat/syndicate,
		/obj/item/clothing/hands/gloves/colored/insulated,
		/obj/item/clothing/hands/gloves/colored/insulated/left,
		/obj/item/clothing/feet/shoes/black_boots,
		/obj/item/clothing/feet/shoes/black_boots/left,
		/obj/item/clothing/belt/storage/colored/black,
		/obj/item/clothing/mask/gas/poly/syndicate,
		/obj/item/clothing/neck/tie/black,
		/obj/item/container/syringe/medipen/hypospray,
		/obj/item/weapon/ranged/bullet/magazine/rifle/syringe,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/magazine/syringe_gun,
		/obj/item/grenade/timed/lube_smoke

	)