//Loads your character instantly at a marker point.
#define ENABLE_INSTALOAD FALSE
#define QUICK_VOTE FALSE
#define SHOW_HOOKS FALSE
#define ENABLE_TRACKS FALSE
#define DEBUG_PATHS FALSE

#define LOAD_GROUND_MAP TRUE
#define ENABLE_STOPLAG TRUE
#define ENABLE_DAMAGE_NUMBERS TRUE



//Game Options


#define BYPASS_AREA_NO_DAMAGE TRUE

#define ENABLE_BULLET_CASINGS FALSE
#define ENABLE_AI TRUE
#define ENABLE_MAPLOAD TRUE
#define ENABLE_LIGHTING TRUE
#define ENABLE_TURFGEN TRUE

#define ENABLE_ATMOS FALSE

#define ENABLE_MOB TRUE
#define ENABLE_WEATHERGEN FALSE
#define ENABLE_HAZARDS FALSE
#define ENABLE_WOUNDS FALSE

#define ENABLE_HIT_MESSAGES FALSE

#define ENABLE_LORE FALSE
#define ENABLE_KARMA FALSE
#define ENABLE_WIKIBOT TRUE
#define ENABLE_SCREEN_MESSAGES FALSE



#define ENABLE_XP TRUE
#define ENABLE_XP_SAVING TRUE
#define LEVEL_CAP 100 //This is the highest possible OVERALL level someone can get.



#define AIR_TEMPERATURE_MOD 3 //How much the air has an impact on reagent temperature.


#define FRIENDLY_FIRE FALSE
#define PLAYER_COLLISIONS FALSE

