#define BULLET_SPEED_MAX                  (TILE_SIZE-1)
#define BULLET_SPEED_SNIPER               BULLET_SPEED_MAX * 1
#define BULLET_SPEED_RIFLE_HEAVY          BULLET_SPEED_MAX * 0.8
#define BULLET_SPEED_RIFLE_LIGHT          BULLET_SPEED_MAX * 0.9
#define BULLET_SPEED_PISTOL_HEAVY         BULLET_SPEED_MAX * 0.7
#define BULLET_SPEED_PISTOL_LIGHT         BULLET_SPEED_MAX * 0.8
#define BULLET_SPEED_LARGE_PROJECTILE     BULLET_SPEED_MAX * 0.6

#define SURPLUS_PENALTY 0.9