
#define CHARGEN_NONE 0x0
#define CHARGEN_COLOR_SKIN 0x1
#define CHARGEN_COLOR_DETAIL 0x2
#define CHARGEN_COLOR_GLOW 0x4
#define CHARGEN_COLOR_EYE 0x8
#define CHARGEN_COLOR_HAIR 0x10
#define CHARGEN_STYLE_HAIR 0x20

#define CHARGEN_SEX 0x40