#define TEXT_WHISPER 0
#define TEXT_TALK 1
#define TEXT_YELL 2
#define TEXT_LOOC 3
#define TEXT_OOC 4
#define TEXT_GHOST 5
#define TEXT_BOT 6
#define TEXT_RADIO 7

#define CHAT_TYPE_SAY 0x1
#define CHAT_TYPE_OOC 0x2
#define CHAT_TYPE_LOOC 0x4
#define CHAT_TYPE_COMBAT 0x8
#define CHAT_TYPE_RADIO 0x10

#define CHAT_TYPE_INFO CHAT_TYPE_SAY