#define MAX_ZOOM 4 //This is for z-zoom.
#define MIN_ZOOM 1

#define MOB_HEIGHT_OFFSET 2
#define STUN_ANGLE -90

#define ATTACK_ANIMATION_LENGTH 1
#define DODGE_ANIMATION_LENGTH 4

#define CHAT_FONT_SIZE 0.25

#define FOOTSTEP_VOLUME 25
#define FOOTPRINT_FADE_TIME SECONDS_TO_DECISECONDS(60)

#define STEALTH_MAX_ALPHA 10
#define STEALTH_MIN_ALPHA 1