#define ATTRIBUTE_STAT 0x1
#define ATTRIBUTE_DAMAGE 0x2
#define ATTRIBUTE_RESISTANCE 0x4

#define ATTRIBUTE_DEFAULT 15

#define ATTRIBUTE_STRENGTH "strength"
#define ATTRIBUTE_VITALITY "vitality"
#define ATTRIBUTE_FORTITUDE "fortitude"

#define ATTRIBUTE_INTELLIGENCE "intelligence"
#define ATTRIBUTE_WISDOM "wisdom"
#define ATTRIBUTE_WILLPOWER "willpower"

#define ATTRIBUTE_DEXTERITY "dexterity"
#define ATTRIBUTE_RESILIENCE "agility"
#define ATTRIBUTE_ENDURANCE "endurance"

#define ATTRIBUTE_LUCK "luck"

#define ATTRIBUTE_LEVEL_S 90
#define ATTRIBUTE_LEVEL_A 75
#define ATTRIBUTE_LEVEL_B 60
#define ATTRIBUTE_LEVEL_C 45
#define ATTRIBUTE_LEVEL_D 30
#define ATTRIBUTE_LEVEL_E 15
#define ATTRIBUTE_LEVEL_F 0

#define SKILL_LEVEL_S 90
#define SKILL_LEVEL_A 75
#define SKILL_LEVEL_B 60
#define SKILL_LEVEL_C 45
#define SKILL_LEVEL_D 30
#define SKILL_LEVEL_E 15
#define SKILL_LEVEL_F 0


#define ATTRIBUTE_STARTING_PRIMARY 25
#define ATTRIBUTE_STARTING_SECONDARY 15
#define ATTRIBUTE_STARTING_TERTIARY 10
#define ATTRIBUTE_STARTING_NONE 5

#define SKILL_STARTING_PRIMARY 25
#define SKILL_STARTING_SECONDARY 15
#define SKILL_STARTING_TERTIARY 10
#define SKILL_STARTING_NONE 5

