#define FACTION_PLAYER "player"
#define FACTION_PLAYER_HOSTILE "player_hostile"




#define RELATIONSHIP_ENEMY -1
#define RELATIONSHIP_NEUTRAL 0
#define RELATIONSHIP_FRIEND 1
#define RELATIONSHIP_ALLY 2

#define ATTACK_ENEMIES -1
#define ATTACK_NEUTRAL 0
#define ATTACK_FRIEND 1
#define ATTACK_ALLY 2