#define FLAG_COLLISION_NONE 0x0
#define FLAG_COLLISION_ETHEREAL 0x1
#define FLAG_COLLISION_WALKING 0x2
#define FLAG_COLLISION_FLYING 0x4
#define FLAG_COLLISION_SWIMMING 0x8

#define FLAG_COLLISION_REAL FLAG_COLLISION_WALKING | FLAG_COLLISION_FLYING | FLAG_COLLISION_SWIMMING


#define FLAG_COLLISION_ALL 0xFFFFFF