

#define FLAGS_HUD_NONE 0x0
#define FLAGS_HUD_MOB 0x1
#define FLAGS_HUD_VEHICLE 0x2
#define FLAGS_HUD_INVENTORY 0x4
#define FLAGS_HUD_SPECIAL 0x8
#define FLAGS_HUD_WORN 0x10
#define FLAGS_HUD_CRAFTING 0x20
#define FLAGS_HUD_CHARGEN 0x40






#define FLAGS_HUD_ALL 0xFFFF