#define FLAG_AREA_NONE 0x0

#define FLAGS_AREA_SAVEZONE 0x1


#define FLAGS_AREA_NO_CONSTRUCTION 0x2
#define FLAGS_AREA_NO_DAMAGE 0x4


#define FLAGS_AREA_SINGLEPLAYER 0x8
#define FLAGS_AREA_ANNOUNCEMENTS 0x10


#define FLAGS_AREA_ROUND_INFORMATION 0x20