#define GAMEMODE_PRELOAD 0
#define GAMEMODE_WAITING 1
#define GAMEMODE_GEARING 2
#define GAMEMODE_BOARDING 3
#define GAMEMODE_LAUNCHING 4
#define GAMEMODE_FIGHTING 5
#define GAMEMODE_BREAK 6

#define WORLD_END_SHUTDOWN 0
#define WORLD_END_NANOTRASEN_VICTORY 1
#define WORLD_END_SYNDICATE_VICTORY 2

#define FAILED "FAILED"
#define COMPLETED "COMPLETED"
#define ACTIVE "ACTIVE"
#define IMPOSSIBLE "IMPOSSIBLE"