#define FLAG_GENERATION_NONE 0x0
#define FLAG_GENERATION_NO_MOB 0x1
#define FLAG_GENERATION_NO_TURF 0x2
#define FLAG_GENERATION_NO_OBJ 0x4


#define GENERATION_SEGMENT_LOWEST 0.1
#define GENERATION_SEGMENT_LOW 0.2
#define GENERATION_SEGMENT_MID 0.5
#define GENERATION_SEGMENT_HIGH 0.8
#define GENERATION_SEGMENT_HIGHEST 0.9

// https://www.desmos.com/calculator/dwjvcmwyk6
#define NOISE_INSTANCES 12
#define NOISE_CURVES 7.3