#define FLAG_GENERATION_NONE 0x0
#define FLAG_GENERATION_NO_MOB 0x1
#define FLAG_GENERATION_NO_TURF 0x2
#define FLAG_GENERATION_NO_OBJ 0x4




#define HEIGHT_WATER_MIN 0
#define HEIGHT_WATER_MAX 0.10
#define HEIGHT_FLOOR_MIN 0.1
#define HEIGHT_FLOOR_MAX 0.75
#define HEIGHT_WALL_MIN 0.75
#define HEIGHT_WALL_MAX 1