//TODO MAKE SPECIES
//#define BLOOD_LEVEL_DEFAULT 570 //We're now confirming that each unit is 10ml
#define BLOOD_DEATH_PERCENT 0.4

#define HEALTH_THRESHOLD_DEAD -50

#define HEALTH_REGEN_BUFFER_MAX 3
#define HEALTH_REGEN_BUFFER_MIN -10

#define STAMINA_REGEN_BUFFER_MAX 10
#define STAMINA_REGEN_BUFFER_MIN -10

#define MANA_REGEN_BUFFER_MAX 10
#define MANA_REGEN_BUFFER_MIN -10

