#define BLOOD_DEATH_PERCENT 0.4

#define HEALTH_REGEN_BUFFER_MAX 3
#define HEALTH_REGEN_BUFFER_MAX_PERCENT 0.01
#define HEALTH_REGEN_BUFFER_MIN -10
#define HEALTH_REGEN_BUFFER_MIN_PERCENT -0.10

#define STAMINA_REGEN_BUFFER_MAX 4
#define STAMINA_REGEN_BUFFER_MAX_PERCENT 0.01
#define STAMINA_REGEN_BUFFER_MIN -10
#define STAMINA_REGEN_BUFFER_MIN_PERCENT 0.10

#define MANA_REGEN_BUFFER_MAX 4
#define MANA_REGEN_BUFFER_MAX_PERCENT 0.01
#define MANA_REGEN_BUFFER_MIN -10
#define MANA_REGEN_BUFFER_MIN_PERCENT -0.05

