#define FLAG_INTERACTION_NONE 0x0
#define FLAG_INTERACTION_LIVING 0x1
#define FLAG_INTERACTION_DEAD 0x2
#define FLAG_INTERACTION_NO_HORIZONTAL 0x4 //Disallow horizontal users.
#define FLAG_INTERACTION_NO_DISTANCE 0x8 //Ignore distance checks.