#define INVISIBILITY_NONE 0
#define INVISIBILITY_AREA 1
#define INVISIBILITY_TURFS 2
#define INVISIBILITY_OBJ 3
#define INVISIBILITY_MOBS 4
#define INVISIBILITY_LIGHTING 5
#define INVISIBILITY_NO_PLAYERS 5
#define INVISIBILITY_PLAYERS 6


#define INVISIBILITY_DEFAULT 10

#define INVISIBLITY_GHOST 90

#define INVISIBILITY_ALL 100
#define INVISIBILITY_ALWAYS 101