#define LANGUAGE_BASIC "basic"
#define LANGUAGE_LIZARD "lizard"
#define LANGUAGE_CULT "cult"
#define LANGUAGE_CODESPEAK "codespeak"
#define LANGUAGE_SLAVIC "slavic"
#define LANGUAGE_CANADIAN "canadian"
#define LANGUAGE_BINARY "binary"
#define LANGUAGE_CLOCKWORK "ratvar"