#define LAYER_AREA AREA_LAYER
#define LAYER_MOB MOB_LAYER
#define LAYER_TURF TURF_LAYER
#define LAYER_OBJ OBJ_LAYER


#define LAYER_FLOOR_DECAL FLOAT_LAYER + 1
#define LAYER_BLOOD FLOAT_LAYER + 2
#define LAYER_FOOTPRINT FLOAT_LAYER + 3


#define PLANE_HUD_TEXT 99
#define PLANE_LIGHTING 100