#define LAYER_FLOOR 1
#define LAYER_FLOOR_LARGE 1.1


#define LAYER_FLOOR_DECAL 2
#define LAYER_WALL 3







#define LAYER_OBJ 4
#define LAYER_MOB 5
#define LAYER_MOB_DAMAGE 6
#define LAYER_MOB_CLOTHING 7
#define LAYER_MOB_HELD 8
#define LAYER_PROJECTILE 9
#define LAYER_EFFECT 10
#define LAYER_GHOST 11
#define LAYER_LIGHTING 12
#define LAYER_AREA 13
#define LAYER_HUD 14
#define LAYER_HUD_ITEMS 15


/*WIP
#define LAYER_MOB_NONE                 LAYER_MOB + 0.01
#define LAYER_MOB_TAIL_BEHIND          LAYER_MOB + 0.02
#define LAYER_MOB_TORSO                LAYER_MOB + 0.03
#define LAYER_MOB_HEAD                 LAYER_MOB + 0.04
#define LAYER_MOB_EAR                  LAYER_MOB + 0.05
#define LAYER_MOB_CLOTHING_EAR         LAYER_MOB_CLOTHING + 0.11
#define LAYER_MOB_EYE                  LAYER_MOB + 0.06
#define LAYER_MOB_CLOTHING_EYE         LAYER_MOB_CLOTHING + 0.10

#define LAYER_MOB_HAIR_HEAD            LAYER_MOB_CLOTHING + 0.13

#define LAYER_MOB_CLOTHING_MASK        LAYER_MOB_CLOTHING + 0.12
#define LAYER_MOB_CLOTHING_HELMET      LAYER_MOB_CLOTHING + 0.14
*/





/* TREE LAYERING
#define LAYER_MOB_NONE                 LAYER_MOB + 0.01
#define LAYER_MOB_TAIL_BEHIND          LAYER_MOB + 0.02

#define LAYER_MOB_TORSO                LAYER_MOB + 0.03

	#define LAYER_MOB_HEAD                 LAYER_MOB + 0.04
		#define LAYER_MOB_EAR                  LAYER_MOB + 0.05
			#define LAYER_MOB_CLOTHING_EAR         LAYER_MOB_CLOTHING + 0.11
		#define LAYER_MOB_EYE                  LAYER_MOB + 0.06
			#define LAYER_MOB_CLOTHING_EYE         LAYER_MOB_CLOTHING + 0.10
		#define LAYER_MOB_CLOTHING_MASK        LAYER_MOB_CLOTHING + 0.12
		#define LAYER_MOB_HAIR_HEAD            LAYER_MOB_CLOTHING + 0.13
			#define LAYER_MOB_CLOTHING_HELMET      LAYER_MOB_CLOTHING + 0.14

	#define LAYER_MOB_GROIN                LAYER_MOB + 0.08
		#define LAYER_MOB_LEGS                 LAYER_MOB + 0.09
			#define LAYER_MOB_FEET                 LAYER_MOB + 0.10
				#define LAYER_MOB_CLOTHING_SHOES       LAYER_MOB_CLOTHING + 0.02

		#define LAYER_MOB_CLOTHING_UNDERWEAR   LAYER_MOB_CLOTHING + 0.01
			#define LAYER_MOB_CLOTHING_PANTS       LAYER_MOB_CLOTHING + 0.04
				#define LAYER_MOB_CLOTHING_UNIFORM     LAYER_MOB_CLOTHING + 0.05
					#define LAYER_MOB_CLOTHING_BELT        LAYER_MOB_CLOTHING + 0.06
						#define LAYER_MOB_CLOTHING_ARMOR       LAYER_MOB_CLOTHING + 0.07
							#define LAYER_MOB_CLOTHING_COAT        LAYER_MOB_CLOTHING + 0.08
								#define LAYER_MOB_CLOTHING_BACK        LAYER_MOB_CLOTHING + 0.09

	#define LAYER_MOB_ARMS                 LAYER_MOB + 0.11
		#define LAYER_MOB_HANDS                LAYER_MOB + 0.12
			#define LAYER_MOB_CLOTHING_GLOVES      LAYER_MOB_CLOTHING + 0.03

#define LAYER_MOB_TAIL_FRONT           LAYER_MOB_CLOTHING + 0.15
*/


/* OLD

#define LAYER_MOB_NONE                 LAYER_MOB + 0.01
#define LAYER_MOB_TAIL_BEHIND          LAYER_MOB + 0.02
#define LAYER_MOB_TORSO                LAYER_MOB + 0.03
#define LAYER_MOB_HEAD                 LAYER_MOB + 0.04
#define LAYER_MOB_EAR                  LAYER_MOB + 0.05
#define LAYER_MOB_EYE                  LAYER_MOB + 0.06
#define LAYER_MOB_MASK                 LAYER_MOB + 0.07
#define LAYER_MOB_GROIN                LAYER_MOB + 0.08
#define LAYER_MOB_LEGS                 LAYER_MOB + 0.09
#define LAYER_MOB_FEET                 LAYER_MOB + 0.10
#define LAYER_MOB_ARMS                 LAYER_MOB + 0.11
#define LAYER_MOB_HANDS                LAYER_MOB + 0.12

#define LAYER_MOB_CLOTHING_UNDERWEAR   LAYER_MOB_CLOTHING + 0.01
#define LAYER_MOB_CLOTHING_SOCKS       LAYER_MOB_CLOTHING + 0.02
#define LAYER_MOB_CLOTHING_SHOES       LAYER_MOB_CLOTHING + 0.03
#define LAYER_MOB_CLOTHING_GLOVES      LAYER_MOB_CLOTHING + 0.04

#define LAYER_MOB_CLOTHING_PANTS       LAYER_MOB_CLOTHING + 0.05
#define LAYER_MOB_CLOTHING_UNIFORM     LAYER_MOB_CLOTHING + 0.06
#define LAYER_MOB_CLOTHING_TIE         LAYER_MOB_CLOTHING + 0.07
#define LAYER_MOB_CLOTHING_BELT        LAYER_MOB_CLOTHING + 0.08
#define LAYER_MOB_CLOTHING_ARMOR       LAYER_MOB_CLOTHING + 0.09
#define LAYER_MOB_CLOTHING_COAT        LAYER_MOB_CLOTHING + 0.10
#define LAYER_MOB_CLOTHING_BACK        LAYER_MOB_CLOTHING + 0.11

#define LAYER_MOB_CLOTHING_EYE         LAYER_MOB_CLOTHING + 0.12
#define LAYER_MOB_CLOTHING_EAR         LAYER_MOB_CLOTHING + 0.13
#define LAYER_MOB_HAIR_HEAD            LAYER_MOB_CLOTHING + 0.14
#define LAYER_MOB_CLOTHING_MASK        LAYER_MOB_CLOTHING + 0.15
#define LAYER_MOB_CLOTHING_HELMET      LAYER_MOB_CLOTHING + 0.16
#define LAYER_MOB_CLOTHING_NECK        LAYER_MOB_CLOTHING + 0.17

#define LAYER_MOB_TAIL_FRONT           LAYER_MOB_CLOTHING + 0.18

#define LAYER_MOB_CLOTHING_OVERALL      LAYER_MOB_CLOTHING + 0.99

*/

#define LAYER_MOB_NONE                 LAYER_MOB + 0.01
#define LAYER_MOB_TAIL_BEHIND          LAYER_MOB + 0.02
#define LAYER_MOB_TORSO                LAYER_MOB + 0.03
#define LAYER_MOB_HEAD                 LAYER_MOB + 0.04
#define LAYER_MOB_EAR                  LAYER_MOB + 0.05
#define LAYER_MOB_EYE                  LAYER_MOB + 0.06
#define LAYER_MOB_MASK                 LAYER_MOB + 0.07
#define LAYER_MOB_GROIN                LAYER_MOB + 0.08
#define LAYER_MOB_LEGS                 LAYER_MOB + 0.09
#define LAYER_MOB_FEET                 LAYER_MOB + 0.10
#define LAYER_MOB_ARMS                 LAYER_MOB + 0.11

#define LAYER_MOB_CLOTHING_UNDERWEAR   LAYER_MOB + 0.12
#define LAYER_MOB_CLOTHING_SOCKS       LAYER_MOB + 0.13
#define LAYER_MOB_CLOTHING_SHOES       LAYER_MOB + 0.14

#define LAYER_MOB_CLOTHING_PANTS       LAYER_MOB + 0.15
#define LAYER_MOB_CLOTHING_UNIFORM     LAYER_MOB + 0.16
#define LAYER_MOB_CLOTHING_TIE         LAYER_MOB + 0.17
#define LAYER_MOB_CLOTHING_BELT        LAYER_MOB + 0.18
#define LAYER_MOB_CLOTHING_ARMOR       LAYER_MOB + 0.19
#define LAYER_MOB_CLOTHING_COAT        LAYER_MOB + 0.20
#define LAYER_MOB_CLOTHING_BACK        LAYER_MOB + 0.21

#define LAYER_MOB_CLOTHING_EYE         LAYER_MOB + 0.22
#define LAYER_MOB_CLOTHING_EAR         LAYER_MOB + 0.23
#define LAYER_MOB_HAIR_HEAD            LAYER_MOB + 0.24
#define LAYER_MOB_CLOTHING_MASK        LAYER_MOB + 0.25
#define LAYER_MOB_CLOTHING_HELMET      LAYER_MOB + 0.26
#define LAYER_MOB_CLOTHING_NECK        LAYER_MOB + 0.27

#define LAYER_MOB_HANDS                LAYER_MOB + 0.28
#define LAYER_MOB_CLOTHING_GLOVES      LAYER_MOB + 0.29
#define LAYER_MOB_HELD                 LAYER_MOB + 0.30

#define LAYER_MOB_CLOTHING_OVER_MOB    LAYER_MOB + 0.31
#define LAYER_MOB_TAIL_FRONT           LAYER_MOB + 0.32
#define LAYER_MOB_CLOTHING_OVERALL     LAYER_MOB + 0.33

