#define FLAG_PERMISSION_NONE 0x0
#define FLAG_PERMISSION_MODERATOR 0x1
#define FLAG_PERMISSION_ADMIN 0x2
#define FLAG_PERMISSION_HOST 0x4

#define FLAG_PERMISSION_DEVELOPER 0x8
#define FLAG_PERMISSION_GAMEMASTER 0x10

#define FLAG_PERMISSION_BRONZE 0x20
#define FLAG_PERMISSION_SILVER 0x40
#define FLAG_PERMISSION_GOLD 0x80

