#define VIEW_RANGE 11
#define ZOOM_RANGE 5

#define WHISPER_RANGE 2
#define TALK_RANGE VIEW_RANGE
#define YELL_RANGE VIEW_RANGE + ZOOM_RANGE

#define SOUND_RANGE VIEW_RANGE + ZOOM_RANGE

#define AI_DETECTION_RANGE VIEW_RANGE * 0.5
#define AI_DETECTION_RANGE_NOISE VIEW_RANGE * 0.75
#define AI_DETECTION_RANGE_CAUTION VIEW_RANGE
#define AI_DETECTION_RANGE_COMBAT VIEW_RANGE + ZOOM_RANGE*0.25

#define BOSS_RANGE VIEW_RANGE + ZOOM_RANGE*2 //If you're out of this range, you're out of the boss fight.
