#define RECIPE(x) SSreagent.all_reagent_recipes[x]

#define REAGENT_ROUNDING 0.01

#define REAGENT_METABOLISM_NONE 0x0
#define REAGENT_METABOLISM_STOMACH 0x1
#define REAGENT_METABOLISM_BLOOD 0x2
#define REAGENT_METABOLISM_SKIN 0x4
#define REAGENT_METABOLISM_PLANT 0x8

#define REAGENT_TEMPERATURE_NONE 0x0
#define REAGENT_TEMPERATURE_NO_AMBIENT 0x1

#define FLAG_FLAVOR_NONE 0x0
#define FLAG_FLAVOR_GROSS 0x1
#define FLAG_FLAVOR_RAW 0x2
#define FLAG_FLAVOR_COOKED 0x4
#define FLAG_FLAVOR_MEAT 0x8
#define FLAG_FLAVOR_FISH 0x10
#define FLAG_FLAVOR_CHICKEN 0x20
#define FLAG_FLAVOR_GRAIN 0x40
#define FLAG_FLAVOR_LOVE 0x80 //Basically means that this took effort to make.
#define FLAG_FLAVOR_JUNK 0x100 //Junkfood.
#define FLAG_FLAVOR_FAT 0x200
#define FLAG_FLAVOR_DAIRY 0x400 //Milk, cheese, ect
#define FLAG_FLAVOR_NECRO 0x800 //Meat from the undead.
#define FLAG_FLAVOR_MEDICINE 0x1000 //Medicine tastes gross.


#define FLAG_REAGENT_NONE 0x0
#define FLAG_REAGENT_RAW 0x1
#define FLAG_REAGENT_COOKED 0x2
#define FLAG_REAGENT_FAT 0x4
#define FLAG_REAGENT_PLANT_FOOD 0x8