#define SOUND_CHANNEL_NONE 0
#define SOUND_CHANNEL_MUSIC 1
#define SOUND_CHANNEL_AMBIENT 2
#define SOUND_CHANNEL_AMBIENT_RANDOM 3
#define SOUND_CHANNEL_UI 4
#define SOUND_CHANNEL_FOOTSTEPS 5
#define SOUND_CHANNEL_FX 6