#define SOUND_CHANNEL_NONE 0
#define SOUND_CHANNEL_MUSIC 1
#define SOUND_CHANNEL_AMBIENT 2


#define SOUND_TYPE_UI "ui"
#define SOUND_TYPE_FOOTSTEPS "foot"
#define SOUND_TYPE_FX "fx"
#define SOUND_TYPE_MUSIC "mus"
#define SOUND_TYPE_AMBIENT "amb"