#define SS_ORDER_CLASS 1
#define SS_ORDER_ATTRIBUTES 2
#define SS_ORDER_SKILLS 3
#define SS_ORDER_FACTIONS 4
#define SS_ORDER_HAIR 5
#define SS_ORDER_SOUND 6
#define SS_ORDER_CLIENT 7
#define SS_ORDER_MOBS 8
#define SS_ORDER_SPAWNPOINTS 9
#define SS_ORDER_THROWING 10
#define SS_ORDER_LIGHTING 11


#define SS_ORDER_SIZE 11