#define SS_ORDER_DMM 1
#define SS_ORDER_WEATHER 2
#define SS_ORDER_TURFS 3
#define SS_ORDER_LIGHTING 4
#define SS_ORDER_DELETE 5

#define SS_ORDER_IMPORTANT 6
#define SS_ORDER_NORMAL 7

#define SS_ORDER_REPORT 8