
#define SS_ORDER_PRELOAD 1
#define SS_ORDER_DMM 2
#define SS_ORDER_WEATHER 3
#define SS_ORDER_TURFS 4
#define SS_ORDER_LIGHTING 5
#define SS_ORDER_DELETE 6

#define SS_ORDER_IMPORTANT 7
#define SS_ORDER_NORMAL 8

#define SS_ORDER_REPORT 9