//All of these are measured in ticks.

#define LIFE_TICK SECONDS_TO_TICKS(1)
#define LIFE_TICK_SLOW SECONDS_TO_TICKS(4)
#define LIFE_TICK_FAST DECISECONDS_TO_TICKS(3)

#define AI_TICK DECISECONDS_TO_TICKS(3)
#define AI_TICK_FAST 2

#define CLIENT_TICK 1
#define CLIENT_TICK_SLOW SECONDS_TO_TICKS(1)

#define PROJECTILE_TICK 1

#define CLIENT_TICKS_PER_SLOW_CLIENT_TICKS (CLIENT_TICK_SLOW / CLIENT_TICK)