//All of these are measured in ticks.

#define LIFE_TICK SECONDS_TO_TICKS(1)
#define LIFE_TICK_SLOW SECONDS_TO_TICKS(4)

#define AI_TICK DECISECONDS_TO_TICKS(1)
#define AI_TICK_FAST DECISECONDS_TO_TICKS(0.5)

#define CLIENT_TICK 3
#define CLIENT_TICK_SLOW SECONDS_TO_TICKS(1)

#define PROJECTILE_TICK 1

#define CLIENT_TICKS_PER_SLOW_CLIENT_TICKS (CLIENT_TICK_SLOW / CLIENT_TICK)
#define LIFE_TICKS_PER_SLOW_LIFE_TICKS (LIFE_TICK_SLOW / LIFE_TICK)