#define FLAG_TOOL_NONE 0x0
#define FLAG_TOOL_SCREWDRIVER 0x1
#define FLAG_TOOL_WRENCH 0x2
#define FLAG_TOOL_CROWBAR 0x4
#define FLAG_TOOL_WELDER 0x8
#define FLAG_TOOL_WIRECUTTER 0x10
#define FLAG_TOOL_MULTITOOL 0x20

#define FLAG_TOOL_PICKAXE 0x40
#define FLAG_TOOL_SHOVEL 0x80