#define FLAG_VISION_NONE 0x0
#define FLAG_VISION_MEDICAL 0x1
#define FLAG_VISION_SECURITY 0x2
#define FLAG_VISION_DIAGNOSTIC 0x4
#define FLAG_VISION_MEDICAL_ADVANCED 0x8

#define FLAG_VISION_ALL 0xFFFFFF