/class/chemist
	name = "The Chemist"
	desc = "Known for their excellent floorpills, the chemist is an absolutely mad scientist. Their knowledge of chemistry and chaos has made them a #1 possible suspect in virtually \
	every chemical related incident."
	id = "chemist"

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_VITALITY = ATTRIBUTE_STARTING_PRIMARY,
		ATTRIBUTE_FORTITUDE = ATTRIBUTE_STARTING_NONE,

		ATTRIBUTE_INTELLIGENCE = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_WISDOM = ATTRIBUTE_STARTING_TERTIARY,
		ATTRIBUTE_WILLPOWER = ATTRIBUTE_STARTING_NONE,

		ATTRIBUTE_DEXTERITY = ATTRIBUTE_STARTING_SECONDARY,
		ATTRIBUTE_AGILITY = ATTRIBUTE_STARTING_NONE,
		ATTRIBUTE_ENDURANCE = ATTRIBUTE_STARTING_TERTIARY,

		ATTRIBUTE_LUCK = 50
	)
	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = SKILL_STARTING_SECONDARY,
		SKILL_DODGE = SKILL_STARTING_NONE,
		 = SKILL_STARTING_NONE,
		 = SKILL_STARTING_NONE,
		SKILL_PRECISION 2 = SKILL_STARTING_NONE,
		SKILL_SURVIVAL 2 = SKILL_STARTING_NONE,

		SKILL_MELEE = SKILL_STARTING_NONE,
		SKILL_BLOCK = SKILL_STARTING_NONE,
		SKILL_UNARMED = SKILL_STARTING_TERTIARY,
		SKILL_PRAYER = SKILL_STARTING_NONE,
		 = SKILL_STARTING_NONE,
		 = SKILL_STARTING_SECONDARY,

		SKILL_MEDICINE = SKILL_STARTING_SECONDARY,
		SKILL_MAGIC = SKILL_STARTING_NONE,
		SKILL_SORCERY 2 = SKILL_STARTING_NONE,
		SKILL_PARRY 2 = SKILL_STARTING_NONE,
		 = SKILL_STARTING_PRIMARY,
		 = SKILL_STARTING_PRIMARY,

		SKILL_ALCHEMY = SKILL_STARTING_PRIMARY,
		SKILL_COOKING = SKILL_STARTING_TERTIARY,
		SKILL_CRAFTING = SKILL_STARTING_TERTIARY,
		SKILL_ENCHANTING = SKILL_STARTING_NONE
	)