/class/gygax

	//Limits:
	//1 ATTRIBUTE_STARTING_PRIMARY
	//2 ATTRIBUTE_STARTING_SECONDARY
	//3 ATTRIBUTE_STARTING_TERTIARY
	//3 ATTRIBUTE_STARTING_NONE
	//Luck untouched
	//10 total attributes
	attributes = list(
		ATTRIBUTE_STRENGTH = 70,
		ATTRIBUTE_VITALITY = 60,
		ATTRIBUTE_FORTITUDE = 90,

		ATTRIBUTE_INTELLIGENCE = 10,
		ATTRIBUTE_WISDOM = 10,
		ATTRIBUTE_WILLPOWER = 10,

		ATTRIBUTE_DEXTERITY = 20,
		ATTRIBUTE_RESILIENCE = 50,
		ATTRIBUTE_ENDURANCE = 60,

		ATTRIBUTE_LUCK = 50
	)


	//Limits
	//3 SKILL_STARTING_PRIMARY
	//3 SKILL_STARTING_SECONDARY
	//3 SKILL_STARTING_TERTIARY
	//13 SKILL_STARTING_NONE
	//22 total skills
	skills = list(
		SKILL_RANGED = 75,
		//SKILL_DODGE  = 75,
		SKILL_PRECISION = 50,
		SKILL_SURVIVAL = 10,

		SKILL_MELEE = 25,
		//SKILL_BLOCK = 50,
		SKILL_UNARMED = 60,
		SKILL_PRAYER = 5,

		SKILL_MEDICINE = 5,
		SKILL_MAGIC = 5,
		SKILL_SORCERY = 5,
		//SKILL_PARRY  = 5,

		SKILL_ALCHEMY = 5,
		SKILL_COOKING = 5,
		SKILL_CRAFTING = 5,
		SKILL_ENCHANTING = 5
	)