/turf/unsimulated/generation/jungle_deep
	name = "deep jungle generation"
	icon_state = "jungle_deep"

/turf/unsimulated/generation/jungle_deep/path
	icon_state = "jungle_deep_path"
	allow_wall = FALSE

/turf/unsimulated/generation/jungle_deep/generate(var/size = WORLD_SIZE)

	var/x_seed = x / size
	var/y_seed = y / size

	var/max_instances = 3
	var/noise = 0
	for(var/i=1,i<=max_instances,i++)
		noise += text2num(rustg_noise_get_at_coordinates("[SSturf.seeds[z+i]]","[x_seed]","[y_seed]"))
	noise *= 1/max_instances
	noise = 0.5 + sin((noise+0.5)*3*180)*0.5


	//More likely to get lava at edges.
	noise -= (abs(x - x/2)/size + abs(y - y/2)/size)*0.5

	switch(noise)
		if(-INFINITY to 0.05)
			if(!allow_wall)
				new /turf/simulated/floor/basalt(src)
			else
				new /turf/simulated/wall/rock/basalt(src)
		if(0.05 to 0.1)
			if(!allow_wall)
				new /turf/simulated/floor/basalt(src)
			else
				new /turf/simulated/liquid/lava(src)
		if(0.1 to 0.11)
			if(!allow_wall && prob(1))
				new /obj/marker/generation/basalt_wall(src)
			else if(prob(2))
				new /obj/marker/generation/mob/ash_walker(src)
			new /turf/simulated/floor/basalt(src)
		if(0.11 to 0.12)
			new /turf/simulated/floor/cave_dirt(src)
		if(0.12 to 0.13)
			if(prob(2))
				new/mob/living/simple/arachnid(src)
			new /turf/simulated/floor/colored/dirt/jungle(src)
		if(0.13 to 0.15)
			if(prob(5))
				new /obj/marker/generation/foliage/grass/jungle/rock(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/tree/jungle(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			if(prob(1))
				new /obj/marker/generation/foliage/jungle_light/stick(src)
			else if(prob(0.25))
				new /obj/marker/generation/mob/arachnid(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			if(prob(1))
				new /obj/marker/generation/mob/cave_spider(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/tree/jungle(src)
			if(prob(1))
				new /obj/marker/generation/mob/goblin(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			if(prob(1))
				new /obj/marker/generation/mob/venus_human_trap(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/tree/jungle(src)
			new /turf/simulated/floor/colored/grass/jungle(src)
		if(0.15 to 0.4)
			if(prob(1))
				new /obj/marker/generation/foliage/jungle_light/flower(src)
				if(prob(0.5))
					new /obj/marker/generation/mob/venus_human_trap(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/jungle_light/mine(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			else if(allow_wall && prob(3))
				new /obj/marker/generation/foliage/tree/jungle(src)
				if(prob(0.5))
					new /obj/marker/generation/jungle_dirt(src)
			else if(allow_wall && prob(1))
				new  /obj/marker/generation/foliage/tree/jungle(src)
				if(prob(1))
					new /obj/marker/generation/jungle_dirt(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/jungle_light/lamp(src)
			if(prob(0.4))
				new /obj/marker/generation/mob/arachnid(src)
			else if(prob(2))
				new /obj/marker/generation/foliage/tree/jungle(src)
			else if(prob(1))
				new /obj/marker/generation/mob/venus_human_trap(src)
			new /turf/simulated/floor/grass/jungle(src)
		if(0.4 to 0.42)
			if(prob(3))
				new /obj/marker/generation/foliage/tree/jungle/small(src)
			if(prob(5))
				new /obj/marker/generation/foliage/grass/jungle/rock(src)
			if(prob(1))
				new /obj/marker/generation/mob/venus_human_trap(src)
			new /turf/simulated/floor/colored/grass/jungle(src)
		if(0.42 to 0.44)
			if(!allow_wall)
				if(prob(1))
					new /obj/marker/generation/jungle_wall(src)
				new /turf/simulated/floor/colored/dirt/jungle(src)
			else
				if(prob(5))
					new /obj/marker/generation/water/jungle(src)
				new /turf/simulated/liquid/water/river/jungle(src)
		if(0.44 to 0.45)
			new /turf/simulated/floor/colored/dirt/jungle(src)
		if(0.45 to 0.47)
			if(!allow_wall)
				new /turf/simulated/floor/colored/dirt/jungle(src)
			else
				if(prob(1))
					new /obj/marker/generation/jungle_wall(src)
				new /turf/simulated/wall/rock/brown(src)
		if(0.47 to 0.48)
			new /turf/simulated/floor/colored/dirt/jungle(src)
		if(0.48 to 0.75)
			if(prob(1))
				new /obj/marker/generation/foliage/grass/jungle(src)
			else if(prob(1))
				new /obj/marker/generation/foliage/jungle_light/flower(src)
			if(prob(1))
				new /obj/marker/generation/mob/venus_human_trap(src)
			if(prob(0.5))
				new /obj/marker/generation/mob/arachnid(src)
			else if(prob(2))
				new /obj/marker/generation/foliage/jungle_light/mine(src)
			else if(allow_wall)
				if(prob(3))
					new /obj/marker/generation/foliage/tree/jungle(src)
					if(prob(0.5))
						new /obj/marker/generation/jungle_dirt(src)
				else if(prob(1))
					new /obj/marker/generation/foliage/tree/jungle(src)
					if(prob(0.5))
						new /obj/marker/generation/jungle_dirt(src)
				else if(prob(1))
					new /obj/marker/generation/foliage/grass/jungle(src)
			new /turf/simulated/floor/grass/jungle(src)
		if(0.75 to 0.85)
			if(prob(5))
				new /obj/marker/generation/foliage/grass/jungle/rock(src)
			else if(prob(3))
				new /obj/marker/generation/foliage/jungle_light/stick(src)
			new /turf/simulated/floor/colored/grass/jungle(src)
		if(0.85 to 0.9)
			if(!allow_wall)
				if(prob(5))
					new /obj/marker/generation/foliage/bushes/fern(src)
				new /turf/simulated/floor/colored/dirt/jungle(src)
			else
				if(prob(1))
					new /obj/marker/generation/jungle_wall(src)
				new /turf/simulated/liquid/water/river/jungle(src)
		if(0.9 to INFINITY)
			if(!allow_wall)
				if(prob(5))
					new /obj/structure/scenery/rocks(src)
				new /turf/simulated/floor/colored/dirt/jungle(src)
			else
				if(prob(5))
					new /obj/marker/generation/water/jungle(src)
				new /turf/simulated/liquid/water/river/jungle(src)

	if(src.loc.type == /area/)
		new /area/mission/jungle/interior(src)

	return ..()
