# Beepsky, Goonstation's replacement for a CI service like Travis, utilizing GitHub Actions
# Based on Turdis by Yogstation
# Stripped down heavily for Burgerstation

name: Beepsky

on:
  pull_request:
    branches: master
  push:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache BYOND
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV
      - name: Compile
        run: |
          tools/ci/dm.sh -DCIBUILD burgerstation.dme
